global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'datacenter', 'app']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email_notification'
receivers:
- name: 'email_notification'
  email_configs:
  - to: your-email@example.com
    from: alertmanager@example.com
    smarthost: smtp.example.com:587
    auth_username: 'smtp-user'
    auth_password: 'smtp-password'

